import fs from 'fs/promises';
import path from 'path';
import os from 'os';
import { getKnowledgeEntries, getTeamMessages, getCrossSessionFindings, upsertKnowledgeEntry } from './memory-db';
import type { KnowledgeEntry, TeamMessage, AutoFinding, KnowledgeCategory, TeamMessageCategory } from './types';
import type { ExtractedKnowledge } from './knowledge-extractor';

const KNOWLEDGE_DIR = '.mlaude';
const KNOWLEDGE_FILE = 'PROJECT-KNOWLEDGE.md';

export interface KnowledgeContext {
  knowledge: string;       // architecture decisions + conventions
  teamMessages: string;    // recent broadcasts
  wontFixSummary: string;  // planner-only: failed findings
}

// Agent role -> relevant knowledge categories
const ROLE_KNOWLEDGE_CATEGORIES: Record<string, KnowledgeCategory[]> = {
  planning_team_lead: ['architecture_decision', 'known_limitation'],
  developer: ['coding_convention', 'resolved_pattern'],
  test_engineer: ['coding_convention', 'resolved_pattern'],
  smoke_tester: ['resolved_pattern'],
};

// Agent role -> relevant team message categories
const ROLE_MESSAGE_CATEGORIES: Record<string, TeamMessageCategory[]> = {
  planning_team_lead: ['architecture', 'warning', 'limitation'],
  developer: ['convention', 'pattern', 'warning'],
  test_engineer: ['convention', 'pattern', 'warning'],
  smoke_tester: ['pattern', 'warning'],
};

export class KnowledgeManager {
  private knowledgePath: string;

  constructor(private projectPath: string) {
    const resolved = projectPath.startsWith('~')
      ? path.join(os.homedir(), projectPath.slice(1))
      : projectPath;
    this.projectPath = resolved;
    this.knowledgePath = path.join(resolved, KNOWLEDGE_DIR, KNOWLEDGE_FILE);
  }

  async readProjectKnowledge(): Promise<string | null> {
    try {
      return await fs.readFile(this.knowledgePath, 'utf-8');
    } catch {
      return null;
    }
  }

  upsertKnowledge(entry: ExtractedKnowledge): void {
    upsertKnowledgeEntry(this.projectPath, entry.title, {
      category: entry.category,
      content: entry.content,
      source_agent: entry.source_agent,
    });
  }

  async syncKnowledgeFile(): Promise<void> {
    const entries = getKnowledgeEntries(this.projectPath);

    const sections: Record<string, KnowledgeEntry[]> = {
      architecture_decision: [],
      coding_convention: [],
      known_limitation: [],
      resolved_pattern: [],
    };

    for (const entry of entries) {
      if (sections[entry.category]) {
        sections[entry.category].push(entry);
      }
    }

    const now = new Date().toISOString();
    const lines: string[] = [
      '# Project Knowledge',
      `> Auto-generated by mlaude. Updated: ${now}`,
      '',
    ];

    const sectionHeaders: Record<string, string> = {
      architecture_decision: 'Architecture Decisions',
      coding_convention: 'Coding Conventions',
      known_limitation: 'Known Limitations',
      resolved_pattern: 'Resolved Patterns',
    };

    for (const [category, header] of Object.entries(sectionHeaders)) {
      lines.push(`## ${header}`);
      const categoryEntries = sections[category];
      if (categoryEntries.length === 0) {
        lines.push('(none)');
      } else {
        for (const entry of categoryEntries) {
          lines.push(`- ${entry.title}: ${entry.content}`);
        }
      }
      lines.push('');
    }

    const dir = path.join(this.projectPath, KNOWLEDGE_DIR);
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(this.knowledgePath, lines.join('\n'), 'utf-8');
  }

  buildKnowledgeContext(agentRole: string, maxChars: number = 3500): KnowledgeContext {
    // 1. Get all knowledge entries for this project
    const allEntries = getKnowledgeEntries(this.projectPath);

    // 2. Get all team messages for this project
    const allMessages = getTeamMessages(this.projectPath, { limit: 50 });

    // 3. Get wont_fix findings for this project
    const wontFixFindings = getCrossSessionFindings(this.projectPath, ['wont_fix']);

    // 4. Filter by agent role
    const relevantCategories = ROLE_KNOWLEDGE_CATEGORIES[agentRole];
    const filteredEntries = relevantCategories
      ? allEntries.filter(e => (relevantCategories as string[]).includes(e.category))
      : allEntries;

    const relevantMessageCategories = ROLE_MESSAGE_CATEGORIES[agentRole];
    const filteredMessages = relevantMessageCategories
      ? allMessages.filter(m => (relevantMessageCategories as string[]).includes(m.category))
      : allMessages;

    // 5. Build text for each section
    const knowledgeBudget = Math.floor(maxChars * 0.6);
    const messagesBudget = Math.floor(maxChars * 0.25);
    const wontFixBudget = Math.floor(maxChars * 0.15);

    const knowledge = this.buildKnowledgeText(filteredEntries, knowledgeBudget);
    const teamMessages = this.buildTeamMessagesText(filteredMessages, messagesBudget);
    const wontFixSummary = this.buildWontFixText(wontFixFindings, wontFixBudget);

    return { knowledge, teamMessages, wontFixSummary };
  }

  private buildKnowledgeText(entries: KnowledgeEntry[], maxLen: number): string {
    if (entries.length === 0) return '';

    const lines: string[] = [];
    let currentLen = 0;

    for (const entry of entries) {
      const line = `- ${entry.title}: ${entry.content}`;
      if (currentLen + line.length + 1 > maxLen) break;
      lines.push(line);
      currentLen += line.length + 1;
    }

    return lines.join('\n');
  }

  private buildTeamMessagesText(messages: TeamMessage[], maxLen: number): string {
    if (messages.length === 0) return '';

    const lines: string[] = [];
    let currentLen = 0;

    for (const msg of messages) {
      const line = `[${msg.category}] ${msg.from_agent}: ${msg.content}`;
      if (currentLen + line.length + 1 > maxLen) break;
      lines.push(line);
      currentLen += line.length + 1;
    }

    return lines.join('\n');
  }

  private buildWontFixText(findings: AutoFinding[], maxLen: number): string {
    if (findings.length === 0) return '';

    const lines: string[] = [];
    let currentLen = 0;

    for (const f of findings) {
      const line = `- ${f.title}: ${f.description}`;
      if (currentLen + line.length + 1 > maxLen) break;
      lines.push(line);
      currentLen += line.length + 1;
    }

    return lines.join('\n');
  }
}
